In [ ]:
import cv2
import numpy as np
import os
import face_recognition as fr
import pyttsx3

In [14]:
path='Images'

In [15]:
os.listdir(path)

['Kohli.jpg', 'LM.jpg', 'Mamooty.jpg', 'MS.jpg', 'Ronaldo.jpg']

In [16]:
mylist=os.listdir(path)
mylist

['Kohli.jpg', 'LM.jpg', 'Mamooty.jpg', 'MS.jpg', 'Ronaldo.jpg']

In [17]:
img=[]
classnames=[]
for i in mylist:
    imgpath=os.path.join(path,i)
    img1=cv2.imread(imgpath)
    #print(img1)
    img.append(img1)

    classnames.append(i.split('.')[0])

In [18]:
print(classnames)

['Kohli', 'LM', 'Mamooty', 'MS', 'Ronaldo']


In [19]:
print(np.__version__)

1.26.0


In [20]:
# img1=img[0]
# cvt_img=cv2.cvtColor(img1,cv2.COLOR_BGR2RGB)
# face_loc=fr.face_locations(cvt_img)
# print(face_loc)
# encoding=fr.face_encodings(cvt_img,face_loc)[0]
# encoding

In [21]:
def faceencodings(images):
    encodelist=[]
    for i in img:
        img1=cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
        face_in_frame=fr.face_locations(img1)
        print(face_in_frame)
        face_encode=fr.face_encodings(img1,face_in_frame)[0]
        encodelist.append(face_encode)
    return encodelist    

In [22]:
faceencodings(img)[0]

[(171, 943, 439, 676)]
[(217, 637, 440, 414)]
[(118, 489, 304, 304)]
[(297, 1067, 759, 605)]
[(162, 1060, 547, 675)]


array([-0.08233187,  0.04915742,  0.03651167, -0.00724757, -0.00151712,
       -0.04501096,  0.01559457,  0.00120675,  0.19175756, -0.04191171,
        0.12548575,  0.04460738, -0.22857858, -0.0653706 , -0.02318984,
        0.0277373 , -0.14064865, -0.12361249, -0.04661581, -0.12974845,
        0.0494804 ,  0.08260341,  0.06053607, -0.00188708, -0.22069211,
       -0.29316279, -0.0422161 , -0.21237345, -0.05979785, -0.15955515,
        0.05897734,  0.05269469, -0.2045137 , -0.05853524, -0.01750889,
        0.06073363,  0.04461041, -0.02987877,  0.1571628 ,  0.04427317,
       -0.08185699, -0.08407177, -0.01204598,  0.30815327,  0.06963657,
       -0.01544365, -0.00861522, -0.02676395,  0.12026473, -0.23901016,
        0.09434908,  0.10439254,  0.0097711 ,  0.05498482,  0.09040833,
       -0.11764255,  0.06126242,  0.04707684, -0.22409345,  0.05000241,
        0.04733766,  0.01663111, -0.02894556, -0.01125385,  0.15516005,
        0.04020098, -0.05361867, -0.06347071,  0.09149466, -0.15

In [23]:
encodelist_knownface=faceencodings(img)

[(171, 943, 439, 676)]
[(217, 637, 440, 414)]
[(118, 489, 304, 304)]
[(297, 1067, 759, 605)]
[(162, 1060, 547, 675)]


In [24]:
video=cv2.VideoCapture(0)
while True:
    suc,img=video.read()
    img1=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    face_loc1=fr.face_locations(img1)
    #print(face_loc1)
    faceencode1=fr.face_encodings(img1,face_loc1)
    for enc_loc,faceloc in zip(faceencode1,face_loc1):
        matches=fr.compare_faces(encodelist_knownface,enc_loc)
        print(matches)
        face_dis=fr.face_distance(encodelist_knownface,enc_loc)
        print(face_dis)
        matchindex=np.argmin(face_dis)
        print(matchindex)
        if matches[matchindex]==True:
            name=classnames[matchindex]
            print(name)

           
            txt_sp=pyttsx3.init()
            voices=txt_sp.getProperty('voices')
            txt_sp.setProperty('voice',voices[1].id)
            txt_sp.setProperty('volume',5)
            txt_sp.setProperty('rate',150)

            txt_sp.say(name)
            txt_sp.runAndWait()

            y1,x2,y2,x1=faceloc
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,0,255),3)
            cv2.putText(img,name,(x1,y1),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,255),3)
        else:
            txt_sp=pyttsx3.init()
            voices=txt_sp.getProperty('voices')
            txt_sp.setProperty('voice',voices[1].id)
            txt_sp.setProperty('volume',5)
            txt_sp.setProperty('rate',150)
            name='unknown'
            txt_sp.say(name)
            txt_sp.runAndWait()
             
            y1,x2,y2,x1=faceloc
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,0,255),3)
            cv2.putText(img,"No match",(x1,y1),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,255),3)
             


    cv2.imshow('Frame',img)
    if cv2.waitKey(1)&0XFF==ord('q'):
        break
video.release()
cv2.destroyAllWindows()    

[False, False, False, False, False]
[0.67293332 0.77003917 0.69110565 0.75842272 0.64327307]
4
[False, False, False, False, False]
[0.67536554 0.79983652 0.70011534 0.75450665 0.64424985]
4
[False, False, False, False, False]
[0.73780992 0.80489386 0.72621356 0.71631912 0.6259193 ]
4
[False, False, False, False, False]
[0.72434561 0.8002689  0.71334791 0.73325842 0.62520533]
4
[False, False, False, False, False]
[0.76477791 0.80551359 0.71223034 0.75604354 0.63616844]
4
[False, False, False, False, False]
[0.69130125 0.8433867  0.74546144 0.79675199 0.64938083]
4
[False, False, False, False, False]
[0.69875095 0.83385363 0.70024788 0.78817802 0.64134504]
4
[False, False, False, False, False]
[0.69528612 0.81832413 0.74752095 0.81272562 0.63075768]
4
[False, False, False, False, False]
[0.69592169 0.77107766 0.72154176 0.78491462 0.62189748]
4
[False, False, False, False, False]
[0.67712438 0.79516978 0.73624589 0.71559518 0.72150073]
0
[False, False, False, False, False]
[0.69526159 0.